# Generated by Django 3.2.19 on 2023-07-02 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20230702_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
