# Generated by Django 3.2.19 on 2023-07-04 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_food_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='data',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
